name: iOS starter workflow

on: workflow_dispatch

jobs:
  build:
    name: Build for iOS
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build iOS Action
        uses: sparkfabrik/ios-build-action@v2.3.2
        with:
          upload-to-testflight: false
          increment-build-number: false
          build-pods: true
          pods-path: "ios/Podfile"
          configuration: Release
          export-method: package
          workspace-path: "ios/Runner.xcworkspace"
          project-path: "ios/Runner.xcodeproj"
          #scheme: Scheme
          output-path: build-${{ github.sha }}.ipa
          #apple-key-id: ${{ secrets.APPLE_KEY_ID }}
          #apple-key-issuer-id: ${{ secrets.APPLE_KEY_ISSUER_ID }}
          #apple-key-content: ${{ secrets.APPLE_KEY_CONTENT }}
          team-id: 7XCUU22SN2
          team-name: Elongaties
          #match-password: ${{ secrets.MATCH_PASSWORD }}
          #match-git-url: ${{ secrets.MATCH_GIT_URL }}
          #match-git-basic-authorization: ${{ secrets.MATCH_GIT_BASIC_AUTHORIZATION }}
          #match-build-type: "appstore"
          browserstack-upload: false
          #browserstack-username: ${{ secrets.BROWSERSTACK_USERNAME }}
          #browserstack-access-key: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
          #fastlane-env: stage
          ios-app-id: xyz.gaties.chanyan
